# Generated by Django 2.2.13 on 2020-07-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressreferee',
            name='referee',
        ),
        migrations.DeleteModel(
            name='AddressCV',
        ),
        migrations.DeleteModel(
            name='AddressReferee',
        ),
    ]
