# Generated by Django 2.2.13 on 2020-07-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200707_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressReferee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=50)),
                ('line_2', models.CharField(blank=True, max_length=50)),
                ('town_city', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=8)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_set', to='accounts.Referee')),
            ],
        ),
        migrations.CreateModel(
            name='AddressCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=50)),
                ('line_2', models.CharField(blank=True, max_length=50)),
                ('town_city', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=8)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_set', to='accounts.CV')),
            ],
        ),
    ]
