# Generated by Django 2.2.13 on 2020-07-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_addresscv_addressreferee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressreferee',
            name='referee',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='education',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='techskill',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='cv',
        ),
        migrations.DeleteModel(
            name='AddressCV',
        ),
        migrations.DeleteModel(
            name='AddressReferee',
        ),
        migrations.DeleteModel(
            name='CV',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Referee',
        ),
        migrations.DeleteModel(
            name='TechSkill',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
