# Generated by Django 2.2.13 on 2020-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_addresscv_addressreferee_cv_education_referee_techskill_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
