# Generated by Django 2.2.13 on 2020-07-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cv_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techskill',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
